# Generated by Django 3.2.2 on 2021-05-14 23:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0007_auto_20210514_1931'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(max_length=1000)),
                ('volumen', models.CharField(max_length=13, verbose_name='Volumen')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.DeleteModel(
            name='Receta',
        ),
        migrations.RenameModel(
            old_name='TipoReceta',
            new_name='Genero',
        ),
        migrations.AddField(
            model_name='manga',
            name='genero',
            field=models.ManyToManyField(to='catalogo.Genero'),
        ),
        migrations.AddField(
            model_name='manga',
            name='mangaka',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogo.mangaka'),
        ),
    ]
